### ISSUE TITLE
video content for AVTrack360 dataset

### ISSUE THREAD

**Issue by dmonkoff** [Telecommunication-Telemedia-Assessment/AVTrack360#1]
It seems like the videos were preprocessed into smaller clips for your AVTrack360 dataset. Could you please add information on how you split those clips? A file with 'video_name-start_ts-length' structure would be very handy. I think files in SRC_info should have contained this data, but it doesn't seem right,for example clips 5 and 6 should have taken different clips from the same video, but start point and length are the same for them.

**Comment by sfremerey** [comment]
Thank you for your interest in AVTrack360.
I've just updated the information on how cutting the SRCs here: https://github.com/Telecommunication-Telemedia-Assessment/AVTrack360/tree/master/AVTrack360_dataset
You can find the exact timestamps now in the respective ffmpeg commands or in the paper itself. Please feel free to ask if you have any further issues.
